baseURL = "https://insectai-cost-action.github.io/"
locale = "en-US"
title = "InsectAI | AI for insect monitoring"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[params]
  description = "InsectAI connects people and open resources for image-based AI in insect monitoring and conservation."
  favicon = "https://avatars.githubusercontent.com/u/174048868?s=64&v=4"
  organizationURL = "https://github.com/InsectAI-COST-Action"
  repositoriesURL = "https://github.com/orgs/InsectAI-COST-Action/repositories"
  costActionURL = "https://www.cost.eu/actions/CA22129/"
  joinURL = "https://www.cost.eu/actions/CA22129/#tabs+Name:Working%20Groups%20and%20Membership"
  officialWebsiteURL = "https://insectai.eu/"